apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-oss-fls.fullname" . }}
  labels:
    {{- include "eric-oss-fls.labels" . | nindent 4 }}
data:
  postgresdb_ip: "10.105.47.180"
  postgresdb_port: "5432"
  service_ip: "10.103.242.149"
  service_port: "8080"

