kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "eric-oss-fls.fullname" . }}-limit-internal-traffic
  labels:
    {{- include "eric-oss-fls.labels" . | nindent 4 }}
spec:
  egress:
  - {}
  ingress:
  - {}
  podSelector:
    matchLabels:
      {{- include "eric-oss-fls.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress

